tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
  stores:
    default:
      defaultCertificate:
        certFile: /traefik/cert.pem
        keyFile: /traefik/key.pem